### ISSUE TITLE
Запускаются все тесты, вместо нужных

### ISSUE THREAD

**Issue by sOlnblshkO** [max-arshinov/dotnet-homeworks-2#21]
Сейчас в master ветке есть домашки(и соответственно тесты) для HW1 и HW2. Сценарий следующий:
1) студент делает HW1
2) проверяет локально тесты - ок
3) создает пр в локальный мастер
4) запускается проверка тестов из HW1 и **HW2**
5) галочка о прохождении тестов не стоит в пре для HW1, так как не все тесты пройдены

**Workaround** для HW1 и HW2: делать в одном пр'е реализацию HW1 и HW2.

**Решение:** нужно последующие домашки заливать в отдельные ветки, а не мержить в мастер, чтобы от них ребята-второкурсники создавали пры в мастер. В таком случае в новом пре будут запускаться нужные тесты

![image](https://user-images.githubusercontent.com/22156715/190202270-2e916049-7eeb-487d-8f6f-6485d596ee91.png)
![image](https://user-images.githubusercontent.com/22156715/190202314-1569d072-723b-4633-afb9-a5df0ceb4c4d.png)

**Comment by MaratElagin** [comment]
Нужно болванки для домашек вынести в отдельную ветку.
HW1 лежит в ветке HW1, HW2 - в ветке HW2.

И режим работы выстроить так:
1. Студенты пулят себе ветку с болванкой очередной домашки
2. Решают домашку. Добиваются прохождения всех workflow.
3. Создают ПР в allHW/master

**Comment by max-arshinov** [comment]
Понял, пушить в мастер было ошибкой. Переделаю на отдельные ветки.

**Comment by max-arshinov** [comment]
исправил @MaratElagin првоеряйте.
